In [105]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import sys

sys.path.append('../')

In [ ]:
from src.metrics import MultiClassMeanRecall,MultiClassMeanPrecision,MultiClassConfusionMatrix

In [101]:


m = MultiClassMeanRecall(num_classes=3)
m.reset_state()

y_true = tf.constant([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = tf.constant([[0.1, 0.8, 0.1], [0.7,0.2,0.1], [0.3,0.6,0.1], [0.1,0.8,0.1]])


m.update_state(y_true, y_pred)
m.result()

y_true = np.array([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = np.array([[0.1,0.8,0.1], [0.7,0.2,0.1], [0.1,0.3,0.6], [0.8,0.1,0.1]])

m.update_state(y_true, y_pred)
m.result()




<tf.Tensor: shape=(), dtype=float64, numpy=0.75>

In [104]:
m = MultiClassMeanPrecision(num_classes=3)
m.reset_state()

y_true = tf.constant([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = tf.constant([[0.1, 0.8, 0.1], [0.7,0.2,0.1], [0.3,0.6,0.1], [0.1,0.8,0.1]])


m.update_state(y_true, y_pred)
m.result()


y_true = np.array([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = np.array([[0.1,0.8,0.1], [0.7,0.2,0.1], [0.1,0.3,0.6], [0.8,0.1,0.1]])

m.update_state(y_true, y_pred)
m.result()


<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [102]:

m = MultiClassConfusionMatrix(num_classes=3)

y_true = np.array([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = np.array([[0.1,0.8,0.1], [0.7,0.2,0.1], [0.3,0.6,0.1], [0.1,0.8,0.1]])
m.update_state(y_true, y_pred)
m.result()

y_true = np.array([[0,1,0], [1,0,0], [0,0,1], [1,0,0]])
y_pred = np.array([[0.1,0.8,0.1], [0.7,0.2,0.1], [0.3,0.6,0.1], [0.1,0.8,0.1]])

m.update_state(y_true, y_pred)
m.result()



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 0],
       [0, 2, 0],
       [0, 2, 0]])>